stages:
    - build
    - unittests
    - publish

build:
    stage: build
    image: microsoft/dotnet:latest
    script:
        # fix https://github.com/dotnet/cli/issues/3681 
        # using https://github.com/dotnet/cli/issues/3681#issuecomment-242912140
        - apt-get update
        - apt-get install unzip
        - mkdir tmp-libs
        - cd tmp-libs
        - wget https://www.nuget.org/api/v2/package/runtime.debian.8-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.4
        - mv 1.0.4 tmp.zip
        - unzip tmp.zip
        - cp ./runtimes/debian.8-x64/lib/netstandard1.0/* /usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.0
        - cp ./runtimes/debian.8-x64/native/* /usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.0
        - cd ..
        - dotnet restore --packages packages
        - dotnet publish -c Release -o output src/b2.Domain.Web
    artifacts:
        expire_in: 1 hrs
        untracked: true
        paths:
            - packages
            - output
            - tmp-libs
unit tests:
    stage: unittests
    image: microsoft/dotnet:latest
    dependencies:
        - build
    script:
        # fix https://github.com/dotnet/cli/issues/3681 
        # using https://github.com/dotnet/cli/issues/3681#issuecomment-242912140
        - cp ./tmp-libs/runtimes/debian.8-x64/lib/netstandard1.0/* /usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.0
        - cp ./tmp-libs/runtimes/debian.8-x64/native/* /usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.0
        - dotnet restore -f packages
        - dotnet test -c Release test/b2.Domain.Tests

publish:
    stage: publish
    image: docker:latest
    services:
        - docker:dind
    dependencies:
        - build
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/xagakure-b2/b2.domain:latest .
        - docker push registry.gitlab.com/xagakure-b2/b2.domain:latest
