stages:
    - build
    - unittests
    - publish

build:
    stage: build
    image: microsoft/dotnet:latest
    script:
        - dotnet restore --packages packages
        - dotnet publish -c Release -o output src/b2.Domain.Web
    artifacts:
        expire_in: 1 hrs
        untracked: true
        paths:
            - packages
            - output
unit tests:
    stage: unittests
    image: microsoft/dotnet:latest
    dependencies:
        - build
    script:
        - dotnet restore -f packages
        - dotnet test -c Release test/b2.Domain.Tests

publish:
    stage: publish
    image: docker:latest
    services:
        - docker:dind
    dependencies:
        - build
    only: 
        - master
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/xagakure-b2/b2.domain:latest .
        - docker push registry.gitlab.com/xagakure-b2/b2.domain:latest
