before_script:
    - dotnet restore

stages:
    - build
    - unittest

build:
    stage: build
    script:
        - dotnet build src/b2.Domain.Web
    tags: 
        - build
        - csharp
        - coreclr

unit tests:
    stage: test
    script:
        - dotnet test test/b2.Domain.Tests
    tags:
        - unit tests
        - xunit
    