image: docker:latest

services:
    - docker:dind

stages:
    - build
    - unittests

build:
    stage: build
    tags: 
        - docker
    script:
        - docker --version
        - docker images 
        - docker build -t b2domain .

unit tests:
    stage: unittests
    tags: 
        - docker
    script:
        - docker run -t b2domain dotnet test -c Release tests/b2.Domain.Tests
