version: '2'
services:
    eventstore:
        image: eventstore/eventstore
        ports:
            - "1113:1113"
            - "2113:2113"
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
    b2domain:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - eventstore
            - rabbitmq
        ports:
            - "5000:5000"